db_uri: 'mysql+pymysql://admin:admin@172.17.0.2:3306/stock'



candidate_code_condition: 'ltsz <= 100 and pe > 0 and pe < 40'
est_begin_date: '2017-10-31'
est_count_start: 5
est_count_step: 5
est_count_end: 25


est_valve_start: 1000
est_valve_step: 500
est_valve_end: 2500



dadan_valve: 500000



msg_send_to: 'eagle'
corpid: 'wx3b381e28fa3192c4'
secret: 'pdCl8v48qRM3XjzzHEnmwGnXcLuKliFoZhq-I7PtALo'


html_file_name: '/var/www/html/index.nginx-debian.html'
image_save_path: '/var/www/html/'
qushi_valve_amount: 50000000
qushi_step_amount: 1000000